all:
  children:
    branch_routers:
      hosts:
        router-warszawa-01:
          ansible_host: 10.0.0.10
          hostname: router-waw-01
          vlan10_ip: 192.168.10.1
          vlan11_ip: 192.168.10.65
          vlan12_ip: 192.168.10.129
          wan_ip: 172.16.100.1
          qos_bandwidth: 19500000

        router-gdansk-01:
          ansible_host: 10.0.0.11
          hostname: router-gda-01
          vlan10_ip: 192.168.11.1
          vlan11_ip: 192.168.11.65
          vlan12_ip: 192.168.11.129
          wan_ip: 172.16.100.5
          qos_bandwidth: 19500000

        router-krakow-01:
          ansible_host: 10.0.0.12
          hostname: router-krk-01
          vlan10_ip: 192.168.12.1
          vlan11_ip: 192.168.12.65
          vlan12_ip: 192.168.12.129
          wan_ip: 172.16.100.9
          qos_bandwidth: 19500000          


      vars:
        ansible_user: changeme
        ansible_password: changeme
        ansible_network_os: cisco.ios.ios
        ansible_connection: network_cli
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: changeme
        #ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"