all:
  children:
    branch_routers:
      hosts:
        router-waw-01:
          ansible_host: 10.0.0.10
          ansible_user: cisco
          ansible_password: cisco
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: cisco